// Generates supabase/seed.sql from data/rosters.json and data/calendar.json.
// Usage: node scripts/generate_seed.mjs   (run join_rosters / parse_calendar first)
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs'
import { teamSlug } from '../src/lib/slug.ts'

const { players, teams } = JSON.parse(readFileSync('data/rosters.json', 'utf8'))
const calendar = JSON.parse(readFileSync('data/calendar.json', 'utf8'))

const q = (s) => `'${String(s).replace(/'/g, "''")}'`
const teamId = new Map(teams.map((t, i) => [t.name, i + 1]))

const slugs = teams.map((t) => teamSlug(t.name))
if (new Set(slugs).size !== teams.length) throw new Error('Team slug collision')

const rows = (list) => list.join(',\n  ')
const out = []
out.push('-- Generated by scripts/generate_seed.mjs. Do not edit by hand.')
out.push('-- Run after migrations/0001_schema.sql.\n')

out.push(
  `insert into teams (id, name, slug, league) values\n  ${rows(
    teams.map((t, i) => `(${i + 1}, ${q(t.name)}, ${q(slugs[i])}, ${q(t.league)})`),
  )};\n`,
)

out.push(
  `insert into players (id, name, role, mantra_roles, serie_a_team) values\n  ${rows(
    players.map((p) => `(${p.id}, ${q(p.name)}, ${q(p.role)}, ${q(p.mantraRoles)}, ${q(p.team)})`),
  )};\n`,
)

// The roster history trigger would log the initial import as 810 "add" rows: skip it here.
out.push('alter table roster_entries disable trigger user;')
out.push(
  `insert into roster_entries (team_id, player_id, cost) values\n  ${rows(
    teams.flatMap((t) => t.roster.map((r) => `(${teamId.get(t.name)}, ${r.playerId}, ${r.cost})`)),
  )};`,
)
out.push('alter table roster_entries enable trigger user;\n')

// Champions matchdays: 8 group rounds, then two legs per knockout round and a single final.
const matchdays = []
for (let n = 1; n <= 8; n++) matchdays.push([n, 'group', 1])
let n = 9
for (const phase of ['playoff', 'r16', 'quarter', 'semi']) {
  matchdays.push([n++, phase, 1], [n++, phase, 2])
}
matchdays.push([n, 'final', 1])
out.push(
  `insert into matchdays (number, phase, leg) values\n  ${rows(
    matchdays.map(([num, phase, leg]) => `(${num}, ${q(phase)}, ${leg})`),
  )};\n`,
)

const fixtures = Object.entries(calendar).flatMap(([md, games]) =>
  games.map((g) => `(${md}, ${teamId.get(g.home)}, ${teamId.get(g.away)})`),
)
out.push(`insert into fixtures (matchday, home_team, away_team) values\n  ${rows(fixtures)};\n`)

mkdirSync('supabase', { recursive: true })
writeFileSync('supabase/seed.sql', out.join('\n'))
console.log(`teams ${teams.length}, players ${players.length}, fixtures ${fixtures.length}, matchdays ${matchdays.length}`)
